# Generated by Django 4.2.4 on 2023-08-26 22:25

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=128, verbose_name="title")),
                (
                    "description",
                    models.TextField(
                        blank=True, max_length=2048, verbose_name="description"
                    ),
                ),
                ("user", models.BooleanField(default=False)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="", verbose_name="image"
                    ),
                ),
                ("time_created", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
