# Generated by Django 4.2.4 on 2023-08-27 00:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_alter_review_body_alter_ticket_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="description",
            field=models.TextField(
                blank=True, max_length=256, verbose_name="description"
            ),
        ),
    ]
