# Generated by Django 4.2.4 on 2023-08-27 15:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_alter_ticket_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="image",
            field=models.ImageField(upload_to="", verbose_name="image"),
        ),
    ]
