# Generated by Django 4.2.4 on 2023-09-06 14:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("AUTHOR", "Auteur"), ("FOLLOWER", "Abonné")],
                max_length=30,
                verbose_name="rôle",
            ),
        ),
    ]
